services:
  mysql:
    image: mysql:8.3
    container_name: mysql-jwt
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq-jwt
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-guest}
    ports:
        - "5672:5672"       # RabbitMQ main port
        - "15672:15672"     # RabbitMQ management UI port
    healthcheck:
        test: [ "CMD", "rabbitmq-diagnostics", "status" ]
        interval: 10s
        timeout: 5s
        retries: 10
    volumes:
        - rabbitmq_data:/var/lib/rabbitmq
        - rabbitmq_logs:/var/log/rabbitmq
    restart: unless-stopped


  app:
    build: .
    container_name: spring-jwt
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      # Database
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}

      # JPA
      JPA_DDL_AUTO: update
      DB_POOL_SIZE: 10

      # JWT
      JWT_SECRET: ${JWT_SECRET}
      ACCESS_EXPIRATION: ${ACCESS_EXPIRATION}
      REFRESH_EXPIRATION: ${REFRESH_EXPIRATION}

      # RabbitMQ
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USER:-guest}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASS:-guest}

      # Customize environment variables as needed
      RABBITMQ_EMAIL_RECOVERY_PASSWORD_QUEUE: ${RABBITMQ_EMAIL_RECOVERY_PASSWORD_QUEUE}
      RABBITMQ_EMAIL_RECOVERY_PASSWORD_EXCHANGE: ${RABBITMQ_EMAIL_RECOVERY_PASSWORD_EXCHANGE}
      RABBITMQ_EMAIL_RECOVERY_PASSWORD_ROUTING_KEY: ${RABBITMQ_EMAIL_RECOVERY_PASSWORD_ROUTING_KEY}

      # DLX / DLQ
      RABBITMQ_APP_DLX: ${RABBITMQ_APP_DLX}
      RABBITMQ_EMAIL_RECOVERY_PASSWORD_DLQ: ${RABBITMQ_EMAIL_RECOVERY_PASSWORD_DLQ}
      RABBITMQ_EMAIL_RECOVERY_PASSWORD_DLQ_ROUTING_KEY: ${RABBITMQ_EMAIL_RECOVERY_PASSWORD_DLQ_ROUTING_KEY}

      # Mailtrap SMTP
      SPRING_MAIL_HOST: smtp.sendgrid.net
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: ${MAIL_USER}
      SPRING_MAIL_PASSWORD: ${MAIL_PASS}
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  mysql-data:
  rabbitmq_data:
  rabbitmq_logs: