server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: jwt

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      initialization-fail-timeout: 60000
      maximum-pool-size: ${DB_POOL_SIZE:10}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:create}
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}

  mail:
    host: ${SPRING_MAIL_HOST:sandbox.smtp.mailtrap.io}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

jwt:
  secret-key: ${JWT_SECRET}
  access-token-expiration-seconds: ${ACCESS_EXPIRATION:900}
  refresh--token-expiration-seconds: ${REFRESH_EXPIRATION:1209600}

rabbitmq:
  dlx:
    name: ${RABBITMQ_APP_DLX}
  email:
    reset:
      queue: ${RABBITMQ_EMAIL_RECOVERY_PASSWORD_QUEUE}
      exchange: ${RABBITMQ_EMAIL_RECOVERY_PASSWORD_EXCHANGE}
      routing-key: ${RABBITMQ_EMAIL_RECOVERY_PASSWORD_ROUTING_KEY}
      dlq: ${RABBITMQ_EMAIL_RECOVERY_PASSWORD_DLQ}
      dlq-routing-key: ${RABBITMQ_EMAIL_RECOVERY_PASSWORD_DLQ_ROUTING_KEY}